### ISSUE TITLE
feat: 채팅 페이지 스타일 추가

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/deal-5#43]
- [x] 채팅 입력창 입력 시 자동 개행
- [x] 채팅 입력창 자동 높이 조절
- [x] 채팅 입력창 일정 높이 이상 커지지 않고 내용 스크롤
- [x] 글자 입력 시 전송 버튼 활성화
- [ ] 스크롤 '채팅'에만 적용
- [x] 채팅방 나가기 버튼 추가
- [x] 채팅방 입장 시 최신 메세지로 자동 스크롤

**Comment by eun-seong** [comment]
텍스트를 가운데 정렬하기 위해 많이 사용된다고..!

```css
line-height: 1.33em; // 줄 간격
vertical-align: top; // 텍스트를 가운데 두기 위해
```

**Comment by eun-seong** [comment]
Alert 컴포넌트를 만들었는데,
알림창이 떴는데도 스크롤이 가능한 문제가 있습니다.

**Comment by eun-seong** [comment]
메세지를 입력하면 전송 버튼이 활성화가 되어야 하는데 부모 컴포넌트에서 자식 컴포넌트의 DOM을 수정하니 부모 컴포넌트 자체가 리렌더링되는 문제가 있습니다.
어떻게 해결하면 좋을지 모르겠습니당,,,

**Comment by HanCheo** [comment]
위에 두문제 이따 오후에 가능하시면 같이 해볼까요?

**Comment by eun-seong** [comment]
#49 랑 겹치는 이슈라서 수정해보겠습니다! 감사합니다:)
