### ISSUE TITLE
feat: 글쓰기 페이지 사진 업로드/삭제 시 이미지 홀더 리렌더링

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/deal-5#49]
글쓰기 페이지에서 사진을 업로드/삭제 할 경우
모든 사진이 리렌더링되는 문제가 있음

삭제/추가 되는 이미지만 리렌더링하게 코드는 변경할 수 있지만,
사진의 개수를 나타내는 컴포넌트를 렌더링하게 되면 같은 이슈(이미지 홀더 전체 리렌더링) 발생

**Comment by HanCheo** [comment]
음....
사진 추가 삭제만 되도록 코드 변경하구
사진 추가 삭제될 때 
사진의 갯수를 나타내는 컴포넌트의 element를 가져와서 innertext로 업데이트 해주는건 어때요??

**Comment by eun-seong** [comment]
언급해주신 방식으로 진행하였습니다!!
