### ISSUE TITLE
bug: 상품 상세 페이지 버튼 잘림

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/deal-5#50]
<img src="https://user-images.githubusercontent.com/49540564/126046997-fb0b8ed5-ff6b-4205-9ed5-1e904cfd39c1.png" width=350/>

크롬에서 아이폰X 로 봤을 때 버튼이 잘려요!

**Comment by HanCheo** [comment]
앗 !!
확인 해쑵니다 수정해서  해당부분 수정해서 올릴께요!
