### ISSUE TITLE
라우터에 파싱 기능 추가

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/deal-5#59]
## TL;DR
* url에 파라미터 추가해서 파싱할 수 있다.
* 파싱된 정보는 컴포넌트에 `$props`로 전달하면 됩니다.
* 추가적으로 middleware 동작도 있어서 얘기해보면 좋겠다!

어제 슬랙으로 잠깐 질문드렸었는데, 궁금해서 하다보니 해결 방법을 찾은 것 같습니다.
FE 조건에 기능 구현에 도움이 되는 외부 라이브러리를 사용할 수 없다고 기재가 되어 있어서 한 번 해봤습니당

지금 라우터에서는 파라미터를 전달할 수 없고 정해진 path로만 가야 하는 상태입니다.
path가 변경되면 `onHashChangeHandler`가 실행됩니다.

현재 이 함수의 첫 부분입니다.
```javascript
const hash = window.location.hash;
const path = hash.substr(1);
const route = this.hasRoute(path) ? this.getRoute(path) : this.getRoute(this.fallback);
```

`localhost:8080/#/chat` 을 입력한 경우,
`hash` : `#/chat`   
`path` : `/chat`
이 들어갑니다.

그래서 `path`에 해당하는 컴포넌트가 있으면 해당 컴포넌트를 반환하고, 아닐 경우 `fallback`(메인 컴포넌트)가 반환됩니다.

url의 `#` 다음에 있는 string이 모두 path로 들어가기 때문에 여기서 파싱을 하면 될 것같아서 한 번 해봤습니다.
1. path에서 `?` 뒤에 있는 모든 문자열을 잘라서 넣어줍니다.
2. `?` 뒤의 문자들을 파싱하여 객체로 저장합니다.

코드로 보면
```javascript
// Router.ts
class Router {
  ...
  async onHashChangeHandler() {
    this.$app.innerHTML = '';
    const hash = window.location.hash;
    /* 변경된 부분 */
    const path = hash.substr(1).replace(/[?]([^#]*)/g, '');
    const params = this.getURLParams(hash);
    const route = this.hasRoute(path) ? this.getRoute(path) : this.getRoute(this.fallback);

    if (route.redirect) {
      this.push(route.redirect);
    ...
  }
  ...
  
  /* 파싱 함수 추가 */
  getURLParams(url: string) {
    let result: {
      [key: string]: string;
    } = {};
    const replacer = (s: string, k: string, v: string, offset: number, str: string) => {
      result[k] = decodeURIComponent(v);
      return '';
    };
    url.replace(/[?&]{1}([^=&#]+)=([^&#]*)/g, replacer);
    return result;
  }
}
```

`localhost:8080/#/chat?id=1&name=eunseong` 에 접속한다고 하면
`hash` : `#/chat?id=1`   
`path` : `/chat`

<img src="https://user-images.githubusercontent.com/49540564/126080680-b4ea2749-fed2-44fb-bd6a-76bfefd69682.png" width=250/>

로 파싱이 되고 `/chat`으로도 접속이 가능해집니다!

파싱된 객체는 렌더링될 때 `$props`로 같이 전달해서 받으면 됩니다!

* * *

추가적으로 지금은 저희가 routes 변수에 path 할당할 때 component만 사용을 하고 있는데,
middleware도 넣을 수 있더라구요.

위의 방법과 같이 사용해보면 좋을 것같습니당

**Comment by HanCheo** [comment]
오 엄청난 꿀팁.....
'엄청 고생하셨네요..ㅠ
확인했습니다 !

프론트 middleware 면 페이지 이동 트랜지션같은거 넣으면 좋을 것같아요 :)
